// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  (typeof exports !== "undefined" && exports !== null ? exports : this).Game = {};

  (typeof exports !== "undefined" && exports !== null ? exports : this).Display = {};

  (typeof exports !== "undefined" && exports !== null ? exports : this).Builder = {};

  locache.cachePrefix += '.canvas1945.';

  locache.expirePrefix += '.canvas1945.';

  locache.cleanup();

}).call(this);
