// Generated by CoffeeScript 1.6.2
(function() {
  (typeof exports !== "undefined" && exports !== null ? exports : this).Game = {};

  (typeof exports !== "undefined" && exports !== null ? exports : this).Display = {};

  (typeof exports !== "undefined" && exports !== null ? exports : this).Builder = {};

}).call(this);
