// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var _this = this;

  window.onload = (function() {
    return (typeof exports !== "undefined" && exports !== null ? exports : _this).Canvas1945 = new Game.Canvas1945();
  });

}).call(this);
