// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  window.onload = ((function(_this) {
    return function() {
      return (typeof exports !== "undefined" && exports !== null ? exports : _this).Canvas1945 = new Game.Canvas1945();
    };
  })(this));

}).call(this);
