// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Game.Container = (function() {
    function Container() {
      this.update = __bind(this.update, this);      this.objects = {};
      this.container = new createjs.Container();
      Object.defineProperty(this, 'createjs', {
        get: function() {
          return this.container;
        }
      });
    }

    Container.prototype.update = function(event) {
      var object, _i, _len, _ref;

      _ref = this.objects;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        object = _ref[_i];
        object.update(event);
      }
      return this;
    };

    Container.prototype.add = function(key, object) {
      if (this.get(key) != null) {
        throw new Error;
      }
      this.objects[key] = object;
      this.container.addChild(object.createjs);
      return this;
    };

    Container.prototype.remove = function(key) {
      var object;

      if ((object = this.get(key)) == null) {
        throw new Error;
      }
      this.container.removeChild(object.createjs);
      delete this.objects[key];
      return this;
    };

    Container.prototype.get = function(key) {
      return this.objects[key];
    };

    return Container;

  })();

}).call(this);
