// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.Game = (function(_super) {
    __extends(Game, _super);

    Game.Width = (function() {
      return 640;
    })();

    Game.Height = (function() {
      return 480;
    })();

    function Game() {
      var canvas, container;

      Game.__super__.constructor.apply(this, arguments);
      canvas = document.createElement('canvas');
      canvas.id = 'game';
      canvas.setAttribute('width', Game.Width);
      canvas.setAttribute('height', Game.Height);
      container = document.getElementById("container");
      container.appendChild(canvas);
      this.stage = this.container = new createjs.Stage(canvas);
      this._setTicker();
    }

    Game.prototype._setTicker = function() {
      createjs.Ticker.addEventListener("tick", this.update);
      createjs.Ticker.useRAF = true;
      createjs.Ticker.setFPS(60);
      return this;
    };

    Game.prototype.getStage = function() {
      return this.stage;
    };

    Game.prototype.update = function(event) {
      Game.__super__.update.call(this, event);
      return this.stage.update();
    };

    return Game;

  })(Game.Container);

}).call(this);
