// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.Movable = (function(_super) {
    __extends(Movable, _super);

    Movable.Direction = {
      up: 'up',
      down: 'down',
      left: 'left',
      right: 'right',
      notup: 'down',
      notdown: 'up',
      notleft: 'right',
      notright: 'left',
      sideup: ['left', 'right'],
      sidedown: ['right', 'left'],
      sideleft: ['down', 'up'],
      sideright: ['up', 'down']
    };

    function Movable(spritesheet, x, y, vx, vy) {
      if (vx == null) {
        vx = 0;
      }
      if (vy == null) {
        vy = 0;
      }
      Movable.__super__.constructor.call(this, spritesheet, x, y);
      this.velocity = {
        x: vx,
        y: vy
      };
    }

    Movable.prototype.update = function(event) {
      var dt;

      if (event.paused) {
        return this;
      }
      dt = event.delta / 1000;
      this.x += dt * this.velocity.x;
      this.y += dt * this.velocity.y;
      return this;
    };

    return Movable;

  })(Game.Sprite);

}).call(this);
