// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.Level = (function(_super) {
    __extends(Level, _super);

    function Level(game) {
      this.game = game;
      Level.__super__.constructor.apply(this, arguments);
      Game.EventManager.on('plane.create', this, this.onPlaneCreated);
      Game.EventManager.on('plane.destroy', this, this.onPlaneDestroyed);
      Game.EventManager.on('bullet.create', this, this.onBulletCreated);
      Game.EventManager.on('bullet.destroy', this, this.onBulletDestroyed);
      Game.EventManager.on('shard.create', this, this.onShardCreated);
      Game.EventManager.on('shard.destroy', this, this.onShardDestroyed);
      Game.EventManager.on('points.get', this, this.onPointsGained);
    }

    Level.prototype.onPlaneCreated = function(source) {
      return this.addTo('level', _.uniqueId('plane'), source);
    };

    Level.prototype.onPlaneDestroyed = function(source) {
      if (source instanceof Game.EnemyPlane) {
        return this.removeFrom('level', this.get('level').findKey(source));
      } else if (source instanceof Game.Player) {
        return this.game.die();
      }
    };

    Level.prototype.onPointsGained = function(source, score) {
      return this.game.data.score += score;
    };

    Level.prototype.onBulletCreated = function(source, bullet) {
      return this.addTo('below', _.uniqueId('bullet'), bullet);
    };

    Level.prototype.onBulletDestroyed = function(source) {
      return this.removeFrom('below', this.get('below').findKey(source));
    };

    Level.prototype.onShardCreated = function(source) {
      return this.addTo('below', _.uniqueId('shard'), source);
    };

    Level.prototype.onShardDestroyed = function(source) {
      return this.removeFrom('below', this.get('below').findKey(source));
    };

    Level.prototype.create = function(level) {
      this.createBackground();
      this.createLayers();
      this.createHeadsUpDisplay();
      return this;
    };

    Level.prototype.createBackground = function() {
      this.game.addTo('background', 'islandA', Builder.BackgroundIsland.create('A'));
      this.game.addTo('background', 'islandB', Builder.BackgroundIsland.create('B'));
      this.game.addTo('background', 'islandC', Builder.BackgroundIsland.create('C'));
      return this;
    };

    Level.prototype.createLayers = function() {
      var blueEnemy, enemy, greenEnemy, i, limeEnemy, orangeEnemy, whiteEnemy, _i, _j, _k, _l, _m, _results;
      this.add('below', new Game.Container());
      this.add('level', new Game.Container());
      this.add('above', new Game.Container());
      this.addTo('level', 'player', this.player = Builder.PlayerPlane.create());
      greenEnemy = new Builder.GreenEnemyPlane().randomPosition().keepLooping();
      whiteEnemy = new Builder.WhiteEnemyPlane().randomPosition().keepLooping();
      orangeEnemy = new Builder.OrangeEnemyPlane().randomPosition().keepLooping();
      blueEnemy = new Builder.BlueEnemyPlane().randomPosition().keepLooping();
      limeEnemy = new Builder.LimeEnemyPlane().randomPosition().keepLooping();
      for (i = _i = 0; _i < 10; i = ++_i) {
        this.addTo('level', 'enemy-' + i, enemy = greenEnemy.create());
      }
      for (i = _j = 10; _j < 20; i = ++_j) {
        this.addTo('level', 'enemy-' + i, enemy = whiteEnemy.create());
      }
      for (i = _k = 20; _k < 30; i = ++_k) {
        this.addTo('level', 'enemy-' + i, enemy = orangeEnemy.create());
      }
      for (i = _l = 30; _l < 40; i = ++_l) {
        this.addTo('level', 'enemy-' + i, enemy = blueEnemy.create());
      }
      _results = [];
      for (i = _m = 40; _m < 50; i = ++_m) {
        _results.push(this.addTo('level', 'enemy-' + i, enemy = limeEnemy.create()));
      }
      return _results;
    };

    Level.prototype.pause = function() {
      return Game.EventManager.trigger('level.paused', this, [true]);
    };

    Level.prototype.resume = function() {
      return Game.EventManager.trigger('level.paused', this, [false]);
    };

    Level.prototype.createHeadsUpDisplay = function() {
      return this.game.addTo('hud', 'bottom', this.hud = new Display.HeadsUpDisplay(this.game, this));
    };

    Level.prototype.clear = function() {
      this.game.get('collisions').clear();
      this.clearBackground();
      this.clearLayers();
      this.clearHeadsUpDisplay();
      return this;
    };

    Level.prototype.kill = function() {
      this.clear();
      Game.EventManager.off('plane.destroy', this, this.onPlaneDestroyed);
      Game.EventManager.off('bullet.create', this, this.onBulletCreated);
      return Game.EventManager.off('bullet.destroy', this, this.onBulletDestroyed);
    };

    Level.prototype.clearBackground = function() {
      this.game.removeFrom('background', 'islandA');
      this.game.removeFrom('background', 'islandB');
      this.game.removeFrom('background', 'islandC');
      return this;
    };

    Level.prototype.clearLayers = function() {
      var i, _i;
      this.removeFrom('level', 'player');
      for (i = _i = 0; _i < 50; i = ++_i) {
        this.removeFrom('level', 'enemy-' + i);
      }
      this.remove('above');
      this.remove('level');
      return this.remove('below');
    };

    Level.prototype.clearHeadsUpDisplay = function() {
      this.game.removeFrom('hud', 'bottom');
      return this;
    };

    Level.prototype.restart = function() {
      this.clear();
      this.create();
      return this;
    };

    return Level;

  })(Game.Container);

}).call(this);
