// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  Game.Level = (function() {
    function Level(game) {
      this.game = game;
      this.create();
    }

    Level.prototype.create = function() {
      this.createBackground();
      this.createPlayer();
      this.createHeadsUpDisplay();
      return this;
    };

    Level.prototype.createBackground = function() {
      this.game.addTo('background', 'islandA', Builder.BackgroundIsland.create('A'));
      this.game.addTo('background', 'islandB', Builder.BackgroundIsland.create('B'));
      this.game.addTo('background', 'islandC', Builder.BackgroundIsland.create('C'));
      return this;
    };

    Level.prototype.createPlayer = function() {
      return this.game.addTo('level', 'player', this.player = Builder.PlanePlayer.create());
    };

    Level.prototype.createHeadsUpDisplay = function() {
      return this.game.addTo('hud', 'bottom', this.hud = new Display.HeadsUpDisplay(this.game, this));
    };

    Level.prototype.clear = function() {
      this.clearBackground();
      this.clearPlayer();
      this.clearHeadsUpDisplay();
      return this;
    };

    Level.prototype.clearBackground = function() {
      this.game.removeFrom('background', 'islandA');
      this.game.removeFrom('background', 'islandB');
      this.game.removeFrom('background', 'islandC');
      return this;
    };

    Level.prototype.clearPlayer = function() {
      this.game.removeFrom('level', 'player');
      return this;
    };

    Level.prototype.clearHeadsUpDisplay = function() {
      this.game.removeFrom('hud', 'hud');
      return this;
    };

    Level.prototype.restart = function() {
      this.clear();
      this.create();
      return this;
    };

    return Level;

  })();

}).call(this);
