// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  Game.Sprite = (function() {
    Sprite.BaseSheet = new createjs.Bitmap("img/1945.png");

    function Sprite(spritesheet, x, y) {
      this.spritesheet = spritesheet;
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      this.animation = new createjs.BitmapAnimation(this.spritesheet);
      this.globalize = _(this.animation.localToGlobal).bind(this.animation);
      Object.defineProperties(this, {
        'createjs': {
          get: function() {
            return this.animation;
          }
        },
        'x': {
          get: function() {
            var _ref;

            return (_ref = this._x) != null ? _ref : 0;
          },
          set: function(value) {
            this._x = value;
            return this.animation.x = (value + .5) | 0;
          }
        },
        'y': {
          get: function() {
            var _ref;

            return (_ref = this._y) != null ? _ref : 0;
          },
          set: function(value) {
            this._y = value;
            return this.animation.y = (value + .5) | 0;
          }
        },
        'width': {
          get: function() {
            return this.animation.getBounds().width;
          }
        },
        'height': {
          get: function() {
            return this.animation.getBounds().height;
          }
        },
        'bounds': {
          get: function() {
            return this.animation.getBounds();
          }
        }
      });
      this.x = x;
      this.y = y;
    }

    Sprite.prototype.play = function(animation) {
      this.createjs.gotoAndPlay(animation);
      return this;
    };

    Sprite.prototype.stop = function(animation) {
      this.createjs.gotoAndStop(animation);
      return this;
    };

    Sprite.prototype.update = function(event) {};

    return Sprite;

  })();

}).call(this);
