// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Display.Menu = (function(_super) {
    __extends(Menu, _super);

    function Menu(gameMenu) {
      var selector;
      this.gameMenu = gameMenu;
      Menu.__super__.constructor.apply(this, arguments);
      this._options = [];
      this._options.push(new createjs.Text("New Game", "12px Arial", "white"));
      this._options.push(new createjs.Text("Resume Game", "12px Arial", "white"));
      this.add('option_new', this._options[0]);
      this.add('option_resume', this._options[1]);
      this._baseX = 280;
      this._options[0].x = this._baseX;
      this._options[1].x = this._baseX;
      this._baseY = 225;
      this._options[0].y = this._baseY;
      this._options[1].y = this._baseY + 20;
      this._selectorSize = 4;
      selector = new createjs.Shape();
      selector.graphics.beginStroke("white");
      selector.graphics.moveTo(0, 0).lineTo(this._selectorSize * 2, this._selectorSize).lineTo(0, this._selectorSize * 2).lineTo(0, 0);
      this.add('selector', selector);
      selector.x = this._baseX - this._selectorSize * 2 - 10;
      selector.y = this._options[this.gameMenu.selectedOption].y + this._selectorSize / 2;
    }

    Menu.prototype.update = function(event) {
      var requestedY;
      Menu.__super__.update.call(this, event);
      requestedY = this._options[this.gameMenu.selectedOption].y + this._selectorSize / 2;
      if (requestedY !== this.get('selector').y) {
        this.get('selector').y = requestedY;
      }
      return this;
    };

    return Menu;

  })(Game.Container);

}).call(this);
