// Generated by CoffeeScript 1.6.2
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Display.FPS = (function() {
    function FPS() {
      this.update = __bind(this.update, this);      this.text = new createjs.Text("?? FPS", "8px Arial", "white");
      this.text.textAlign = 'right';
      this.text.x = Game.Canvas1945.Width - 5;
      this.text.y = 5;
      Object.defineProperty(this, 'createjs', {
        get: function() {
          return this.text;
        }
      });
      this._frameCount = 0;
      this._frameRate = 0;
      this._time = 0;
    }

    FPS.prototype.update = function(event) {
      if ((this._time += event.delta) >= 1000) {
        this._frameRate = this._frameCount;
        this._frameCount = 0;
        this._time -= 1000;
        this.text.text = "" + this._frameRate + " FPS";
      }
      return this._frameCount++;
    };

    return FPS;

  })();

}).call(this);
