// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';  Game.Data = (function() {
    function Data() {
      this.lives = 3;
      this.score = 0;
      this.level = 0;
    }

    return Data;

  })();

}).call(this);
