// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.PlayerBullet = (function(_super) {
    __extends(PlayerBullet, _super);

    function PlayerBullet(spritesheet, x, y, vx, vy, type, damage, args) {
      if (vx == null) {
        vx = 0;
      }
      if (vy == null) {
        vy = -300;
      }
      if (type == null) {
        type = 'up';
      }
      if (damage == null) {
        damage = 3;
      }
      if (args == null) {
        args = {};
      }
      PlayerBullet.__super__.constructor.call(this, spritesheet, x, y, vx, vy, type, damage, args);
      Game.EventManager.trigger('collidable.create', this, [Game.CollisionManager.Groups.PlayerBullet, this]);
    }

    PlayerBullet.prototype.destroy = function() {
      PlayerBullet.__super__.destroy.apply(this, arguments);
      Game.EventManager.trigger('collidable.destroy', this, [Game.CollisionManager.Groups.PlayerBullet, this]);
      return this;
    };

    return PlayerBullet;

  })(Game.Bullet);

}).call(this);
