// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.Bullet = (function(_super) {
    __extends(Bullet, _super);

    function Bullet(spritesheet, x, y, vx, vy, type, damage, args) {
      if (type == null) {
        type = 'point';
      }
      if (damage == null) {
        damage = 1;
      }
      if (args == null) {
        args = {};
      }
      Bullet.__super__.constructor.call(this, spritesheet, x, y, vx, vy);
      this.damage = damage;
      this.play(type);
    }

    Bullet.prototype.update = function(event) {
      if (event.paused) {
        return;
      }
      Bullet.__super__.update.call(this, event);
      if (this.y < -64 || this.y > Game.Canvas1945.Height || this.x < -64 || this.x > Game.Canvas1945.Width + 64) {
        this.destroy();
      }
      return this;
    };

    Bullet.prototype.collide = function(group, object) {
      return this.destroy();
    };

    Bullet.prototype.destroy = function() {
      Bullet.__super__.destroy.apply(this, arguments);
      Game.EventManager.trigger('bullet.destroy', this, []);
      return this;
    };

    return Bullet;

  })(Game.Movable);

}).call(this);
