// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.EnemyBullet = (function(_super) {
    __extends(EnemyBullet, _super);

    function EnemyBullet(spritesheet, x, y, vx, vy, type, damage, args) {
      if (vy == null) {
        vy = 150 + 100;
      }
      if (type == null) {
        type = 'point';
      }
      if (damage == null) {
        damage = 1;
      }
      if (args == null) {
        args = {};
      }
      EnemyBullet.__super__.constructor.call(this, spritesheet, x, y, vx, vy, type, damage, args);
      Game.EventManager.trigger('collidable.create', this, [Game.CollisionManager.Groups.EnemyBullet, this]);
    }

    EnemyBullet.prototype.destroy = function() {
      EnemyBullet.__super__.destroy.apply(this, arguments);
      Game.EventManager.trigger('collidable.destroy', this, [Game.CollisionManager.Groups.EnemyBullet, this]);
      return this;
    };

    return EnemyBullet;

  })(Game.Bullet);

}).call(this);
