// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.Island = (function(_super) {
    __extends(Island, _super);

    Island.Padding = 50;

    function Island(spritesheet, type) {
      var rel;

      if (type == null) {
        type = 'A';
      }
      Island.__super__.constructor.call(this, spritesheet);
      this.createjs.gotoAndStop('type-' + type);
      this.x = Math.random() * Game.Canvas1945.Width;
      rel = Math.floor(Math.random() * (Game.Canvas1945.Height / 3 - Island.Padding));
      switch (type) {
        case 'A':
          this.y = rel;
          break;
        case 'B':
          this.y = rel + Game.Canvas1945.Height / 3 * 1;
          break;
        case 'C':
          this.y = rel + Game.Canvas1945.Height / 3 * 2;
      }
    }

    Island.prototype.update = function(event) {
      var dt;

      if (event.paused) {
        return;
      }
      dt = event.delta / 1000;
      this.y += dt * Game.Canvas1945.ScrollSpeed;
      if (this.y > Game.Canvas1945.Height + Island.Padding) {
        this.y = -Island.Padding;
        return this.x = Math.random() * Game.Canvas1945.Width;
      }
    };

    return Island;

  })(Game.Sprite);

}).call(this);
