// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Game.Player = (function(_super) {
    __extends(Player, _super);

    function Player(spritesheet) {
      Player.__super__.constructor.call(this, spritesheet);
      this.x = 100;
      this.y = 100;
      this.play('idle');
    }

    Player.prototype.update = function(event) {
      if (event.paused) {

      }
    };

    return Player;

  })(Game.Sprite);

}).call(this);
