// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.BackgroundIsland = (function(_super) {
    __extends(BackgroundIsland, _super);

    function BackgroundIsland() {
      _ref = BackgroundIsland.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BackgroundIsland.SpriteSheet = null;

    BackgroundIsland.create = function(type) {
      var builder;

      if (BackgroundIsland.SpriteSheet != null) {
        return new Game.Island(BackgroundIsland.SpriteSheet, type);
      }
      builder = new Builder.BackgroundIsland();
      builder.animation('type-A', 103, 499, 64, 65, 1, 1, 1, 1);
      builder.animation('type-B', 168, 499, 64, 65, 1, 1, 1, 1);
      builder.animation('type-C', 233, 499, 64, 65, 1, 1, 1, 1);
      BackgroundIsland.SpriteSheet = builder.createjs;
      return new Game.Island(BackgroundIsland.SpriteSheet, type);
    };

    return BackgroundIsland;

  })(Builder.SpriteSheet);

}).call(this);
