// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.PlaneMini = (function(_super) {
    __extends(PlaneMini, _super);

    function PlaneMini() {
      _ref = PlaneMini.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PlaneMini.SpriteSheet = null;

    PlaneMini.create = function() {
      var builder;

      if (PlaneMini.SpriteSheet != null) {
        return new Game.Sprite(PlaneMini.SpriteSheet);
      }
      builder = new Builder.PlaneMini();
      builder.animation('+5dir', 4, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('+3dir', 37, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('+2dir', 70, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('stones', 103, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('shield', 136, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('blue', 169, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('mini', 202, 268, 32, 32, 1, 1, 1, 1);
      builder.animation('pow', 235, 235, 32, 32, 1, 1, 1, 2);
      builder.animation('up', 202, 235, 32, 32, 1, 1, 1, 1);
      PlaneMini.SpriteSheet = builder.createjs;
      return new Game.Sprite(PlaneMini.SpriteSheet);
    };

    return PlaneMini;

  })(Builder.SpriteSheet);

}).call(this);
