// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.LimeEnemyPlane = (function(_super) {
    __extends(LimeEnemyPlane, _super);

    function LimeEnemyPlane() {
      return LimeEnemyPlane.__super__.constructor.apply(this, arguments);
    }

    LimeEnemyPlane.SpriteSheet = null;

    LimeEnemyPlane.prototype.create = function() {
      var builder;
      if (LimeEnemyPlane.SpriteSheet != null) {
        return (new Game.EnemyPlane(LimeEnemyPlane.SpriteSheet)).addBehaviours(this.getBehaviours());
      }
      builder = new Builder.LimeEnemyPlane();
      builder.animationExtra('idle', 202, 466, 32, 32, 1, 1, 3, 3, true, 2);
      builder.animationExtra('explode', 70, 169, 32, 32, 1, 1, 6, 6, 'hide', 4);
      builder.animationExtra('hide', 268, 202, 32, 32, 1, 1, 1, 1, false, 1);
      builder.animationExtra('loop', 664, 203, 32, 32, 1, 1, 1, 5, 'upside', 2);
      builder.animation('upside', 4, 367, 32, 32, 1, 1, 2, 2);
      builder.data.animations['upside'].frames.push(_.last(builder.data.animations['loop'].frames));
      LimeEnemyPlane.SpriteSheet = builder.createjs;
      return (new Game.EnemyPlane(LimeEnemyPlane.SpriteSheet)).addBehaviours(this.getBehaviours());
    };

    return LimeEnemyPlane;

  })(Builder.EnemyPlane);

}).call(this);
