// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.OrangeEnemyPlane = (function(_super) {
    __extends(OrangeEnemyPlane, _super);

    function OrangeEnemyPlane() {
      _ref = OrangeEnemyPlane.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    OrangeEnemyPlane.SpriteSheet = null;

    OrangeEnemyPlane.create = function() {
      var builder;

      if (OrangeEnemyPlane.SpriteSheet != null) {
        return (new Game.EnemyPlane(OrangeEnemyPlane.SpriteSheet)).addBehaviour(Game.EnemyPlane.Behaviour.looper).addBehaviour(Game.EnemyPlane.Behaviour.spawn.random.x).addBehaviour(Game.EnemyPlane.Behaviour.spawn.random.y).addBehaviour(Game.EnemyPlane.Behaviour.spawn.ondeath);
      }
      builder = new Builder.OrangeEnemyPlane();
      builder.animationExtra('idle', 4, 499, 32, 32, 1, 1, 3, 3, true, 2);
      builder.animationExtra('explode', 70, 169, 32, 32, 1, 1, 6, 6, 'hide', 2);
      builder.animationExtra('hide', 268, 202, 32, 32, 1, 1, 1, 1, false, 1);
      OrangeEnemyPlane.SpriteSheet = builder.createjs;
      return (new Game.EnemyPlane(OrangeEnemyPlane.SpriteSheet)).addBehaviour(Game.EnemyPlane.Behaviour.looper).addBehaviour(Game.EnemyPlane.Behaviour.spawn.random.x).addBehaviour(Game.EnemyPlane.Behaviour.spawn.random.y).addBehaviour(Game.EnemyPlane.Behaviour.spawn.ondeath);
    };

    return OrangeEnemyPlane;

  })(Builder.SpriteSheet);

}).call(this);
