// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.GreenEnemyPlane = (function(_super) {
    __extends(GreenEnemyPlane, _super);

    function GreenEnemyPlane() {
      return GreenEnemyPlane.__super__.constructor.apply(this, arguments);
    }

    GreenEnemyPlane.SpriteSheet = null;

    GreenEnemyPlane.prototype.create = function() {
      var builder;
      if (GreenEnemyPlane.SpriteSheet != null) {
        return GreenEnemyPlane.__super__.create.call(this, new Game.EnemyPlane(GreenEnemyPlane.SpriteSheet)).addBehaviours(this.getBehaviours());
      }
      builder = new Builder.GreenEnemyPlane();
      builder.animationExtra('idle', 4, 466, 32, 32, 1, 1, 3, 3, true, 2);
      builder.animationExtra('explode', 70, 169, 32, 32, 1, 1, 6, 6, 'hide', 4);
      builder.animationExtra('hide', 268, 202, 32, 32, 1, 1, 1, 1, false, 1);
      builder.animationExtra('loop', 598, 203, 32, 32, 1, 1, 1, 5, 'upside', 2);
      builder.animation('upside', 136, 367, 32, 32, 1, 1, 2, 2);
      builder.data.animations['upside'].frames.push(_.last(builder.data.animations['loop'].frames));
      GreenEnemyPlane.SpriteSheet = builder.createjs;
      return GreenEnemyPlane.__super__.create.call(this, new Game.EnemyPlane(GreenEnemyPlane.SpriteSheet)).addBehaviours(this.getBehaviours());
    };

    return GreenEnemyPlane;

  })(Builder.EnemyPlane);

}).call(this);
