// Generated by CoffeeScript 1.6.2
(function() {
  'use strict';
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.PlanePlayer = (function(_super) {
    __extends(PlanePlayer, _super);

    function PlanePlayer() {
      _ref = PlanePlayer.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PlanePlayer.SpriteSheet = null;

    PlanePlayer.create = function() {
      var builder;

      if (PlanePlayer.SpriteSheet != null) {
        return new Game.Player(PlanePlayer.SpriteSheet);
      }
      builder = new Builder.PlanePlayer();
      builder.animation('idle', 4, 400, 65, 65, 1, 1, 3, 3);
      builder.animation('explode', 4, 301, 65, 65, 1, 1, 7, 7);
      PlanePlayer.SpriteSheet = builder.createjs;
      return new Game.Player(PlanePlayer.SpriteSheet);
    };

    return PlanePlayer;

  })(Builder.SpriteSheet);

}).call(this);
