// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Builder.Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      _ref = Player.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Player.create = function(callback) {
      var builder;

      builder = new Builder.Player();
      builder.animation('idle', 4, 400, 65, 65, 1, 1, 3, 3);
      builder.animation('explode', 4, 301, 65, 65, 1, 1, 7, 7);
      builder.createjs.addEventListener('complete', callback);
      return builder.createjs.buildAsync();
    };

    return Player;

  })(Builder.SpriteSheet);

}).call(this);
