// Generated by CoffeeScript 1.6.2
(function() {
  var __slice = [].slice;

  Builder.SpriteSheet = (function() {
    function SpriteSheet() {
      this.builder = new createjs.SpriteSheetBuilder();
      Object.defineProperty(this, 'createjs', {
        get: function() {
          return this.builder;
        }
      });
    }

    SpriteSheet.prototype.sequence = function(x, y, w, h, gx, gy, xlen, len) {
      var i, i_x, i_y, sequence, _i;

      if (len == null) {
        len = xlen;
      }
      sequence = [];
      for (i = _i = 0; 0 <= len ? _i < len : _i > len; i = 0 <= len ? ++_i : --_i) {
        i_x = x + ((w + gx) * (i % xlen));
        i_y = y + ((y + gy) * Math.floor(i / xlen));
        sequence.push(this.builder.addFrame(Game.Sprite.BaseSheet, new createjs.Rectangle(i_x, i_y, w, h)));
      }
      return sequence;
    };

    SpriteSheet.prototype.animation = function() {
      var animation, s;

      animation = arguments[0], s = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      this.builder.addAnimation(animation, this.sequence.apply(this, s));
      return this;
    };

    SpriteSheet.prototype.animationExtra = function() {
      var animation, frequency, next, s, _i;

      animation = arguments[0], s = 4 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 2) : (_i = 1, []), next = arguments[_i++], frequency = arguments[_i++];
      this.builder.addAnimation(animation, this.sequence.apply(this, s), next, frequency);
      return this;
    };

    return SpriteSheet;

  })();

}).call(this);
