// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Levels.Endless = (function(_super) {
    __extends(Endless, _super);

    function Endless() {
      return Endless.__super__.constructor.apply(this, arguments);
    }

    return Endless;

  })(Levels.Base);

}).call(this);
