// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Levels.Level1 = (function(_super) {
    __extends(Level1, _super);

    function Level1() {
      return Level1.__super__.constructor.apply(this, arguments);
    }

    Level1.prototype.injectInto = function(gameLevel) {
      var greenEnemy, s;
      Level1.__super__.injectInto.call(this, gameLevel);
      greenEnemy = new Builder.GreenEnemyPlane();
      s = 1000;
      this.timeline = new Game.Timeline();
      this.timeline.add(1 * s, greenEnemy.positionX(20).create());
      this.timeline.add(1.1 * s, greenEnemy.positionX(80).create());
      this.timeline.add(1.2 * s, greenEnemy.positionX(140).create());
      this.timeline.add(1.3 * s, greenEnemy.positionX(80).create());
      this.timeline.add(1.4 * s, greenEnemy.positionX(140).create());
      this.timeline.add(1.5 * s, greenEnemy.positionX(200).create());
      this.timeline.add(1.6 * s, greenEnemy.positionX(140).create());
      this.timeline.add(1.7 * s, greenEnemy.positionX(200).create());
      this.timeline.add(1.8 * s, greenEnemy.positionX(260).create());
      this.timeline.add(1.9 * s, greenEnemy.positionX(200).create());
      this.timeline.add(2.0 * s, greenEnemy.positionX(260).create());
      this.timeline.add(2.1 * s, greenEnemy.positionX(320).create());
      this.timeline.add(5 * s, {
        spawn: function() {}
      });
      return this.timeline.prepare();
    };

    Level1.prototype.update = function(event) {
      if (this.timeline.update(event).isDone) {
        return _.defer(this.gameLevel.finish, 2);
      }
    };

    return Level1;

  })(Levels.Base);

}).call(this);
