// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Levels.Endless = (function(_super) {
    __extends(Endless, _super);

    function Endless() {
      return Endless.__super__.constructor.apply(this, arguments);
    }

    Endless.prototype.injectInto = function(gameLevel) {
      var blueEnemy, greenEnemy, i, limeEnemy, orangeEnemy, whiteEnemy, _i, _j, _k, _l, _m, _results;
      Endless.__super__.injectInto.call(this, gameLevel);
      greenEnemy = new Builder.GreenEnemyPlane().randomPosition().keepLooping().keepRespawning();
      whiteEnemy = new Builder.WhiteEnemyPlane().randomPosition().keepLooping().keepRespawning();
      orangeEnemy = new Builder.OrangeEnemyPlane().randomPosition().keepLooping().keepRespawning();
      blueEnemy = new Builder.BlueEnemyPlane().randomPosition().keepLooping().keepRespawning();
      limeEnemy = new Builder.LimeEnemyPlane().randomPosition().keepLooping().keepRespawning();
      for (i = _i = 0; _i < 10; i = ++_i) {
        greenEnemy.create().spawn();
      }
      for (i = _j = 10; _j < 20; i = ++_j) {
        whiteEnemy.create().spawn();
      }
      for (i = _k = 20; _k < 30; i = ++_k) {
        orangeEnemy.create().spawn();
      }
      for (i = _l = 30; _l < 40; i = ++_l) {
        blueEnemy.create().spawn();
      }
      _results = [];
      for (i = _m = 40; _m < 50; i = ++_m) {
        _results.push(limeEnemy.create().spawn());
      }
      return _results;
    };

    return Endless;

  })(Levels.Base);

}).call(this);
