// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Levels.Level0 = (function(_super) {
    __extends(Level0, _super);

    function Level0() {
      return Level0.__super__.constructor.apply(this, arguments);
    }

    Level0.prototype.injectInto = function(gameLevel) {
      var blueEnemy, greenEnemy, i, limeEnemy, orangeEnemy, whiteEnemy, _i, _j, _k, _l, _m, _results;
      Level0.__super__.injectInto.call(this, gameLevel);
      greenEnemy = new Builder.GreenEnemyPlane().randomPosition().keepLooping();
      whiteEnemy = new Builder.WhiteEnemyPlane().randomPosition().keepLooping();
      orangeEnemy = new Builder.OrangeEnemyPlane().randomPosition().keepLooping();
      blueEnemy = new Builder.BlueEnemyPlane().randomPosition().keepLooping();
      limeEnemy = new Builder.LimeEnemyPlane().randomPosition().keepLooping();
      for (i = _i = 0; _i < 10; i = ++_i) {
        greenEnemy.create();
      }
      for (i = _j = 10; _j < 20; i = ++_j) {
        whiteEnemy.create();
      }
      for (i = _k = 20; _k < 30; i = ++_k) {
        orangeEnemy.create();
      }
      for (i = _l = 30; _l < 40; i = ++_l) {
        blueEnemy.create();
      }
      _results = [];
      for (i = _m = 40; _m < 50; i = ++_m) {
        _results.push(limeEnemy.create());
      }
      return _results;
    };

    Level0.prototype.planeDestroyed = function() {
      Level0.__super__.planeDestroyed.apply(this, arguments);
      if (this.enemyCount === 0) {
        return _.defer(this.gameLevel.finish, 1);
      }
    };

    return Level0;

  })(Levels.Base);

}).call(this);
